name: CI + CD

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 ${GITHUB_REF#refs/heads/}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    environment:
      name: dev
      url: https://${{github.sha}}-dev.domainas.lt
    steps:
      - name: Step 1
        run: echo "Step 1"
  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    environment:
      name: stage
      url: https://${{github.sha}}-stage.domainas.lt
    steps:
      - name: Step 1
        run: echo "Step 1 ${GITHUB_SHA}"
      - name: Step 2
        run: echo "Step 1 ${GITHUB_REF#refs/heads/}"
  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    if: failure()
    steps:
    - name: Step 1
      run: echo "Rolling back ${GITHUB_SHA}"
